apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
vars:
- fieldref:
    fieldPath: data.CHECKMKPROXY_DNS_LABEL
  name: CHECKMKPROXY_DNS_LABEL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- config.yaml
